version: "3.8"

services:
  # -------------------- USER SERVICE --------------------
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo-user-db
    environment:
      - PORT=5000
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=secret
      - MONGO_DB_NAME=userdb

  mongo-user-db:
    image: mongo
    container_name: mongo-user-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=userdb
    ports:
      - "27018:27017"

  # -------------------- PRODUCT SERVICE --------------------
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5001:5001"
    depends_on:
      - mongo-product-db
    environment:
      - PORT=5001
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=secret
      - MONGO_DB_NAME=productdb

  mongo-product-db:
    image: mongo
    container_name: mongo-product-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=productdb
    ports:
      - "27019:27017"
