version: "3.8"

services:
  # ========================
  # User Service + MongoDB
  # ========================
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "1234:1234"
    depends_on:
      - mongo-user-db
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB_NAME=userdb
      - JWT_SECRET=mysecret123
      - PORT=1234
    networks:
      - app-network

  mongo-user-db:
    image: mongo:7
    container_name: mongo-user-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: userdb
    ports:
      - "27017:27017"
    volumes:
      - mongo-user-data:/data/db
    networks:
      - app-network

  # ========================
  # Product Service + MongoDB
  # ========================
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "5678:5678"
    depends_on:
      - mongo-product-db
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB_NAME=productdb
      - PORT=5678
    networks:
      - app-network

  mongo-product-db:
    image: mongo:7
    container_name: mongo-product-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: productdb
    ports:
      - "27018:27017" # avoid clash with mongo-user-db
    volumes:
      - mongo-product-data:/data/db
    networks:
      - app-network

# ========================
# Volumes & Network
# ========================
volumes:
  mongo-user-data:
  mongo-product-data:

networks:
  app-network:
